from enum import Enum


class DeviceType(Enum):
    VAC_360_EYE = "N223"
    VAC_360_HEURIST = "276"
    VAC_360_VIS_NAV = "277"
    PURE_COOL_LINK_DESK = "469"  
    PURE_COOL_DESK = "520"  
    PURE_COOL_LINK = "475"  
    PURE_COOL = "438"  
    PURIFIER_COOL_K = "438K"  
    PURIFIER_COOL_E = "438E"  
    PURIFIER_COOL_M = "438M"  
    PURE_HUMIDIFY_COOL = "358"  
    PURIFIER_HUMIDIFY_COOL_K = "358K"  
    PURIFIER_HUMIDIFY_COOL_E = "358E"  
    PURE_HOT_COOL_LINK = "455"  
    PURE_HOT_COOL = "527"  
    PURIFIER_HOT_COOL_E = "527E"  
    PURIFIER_HOT_COOL_K = "527K"  
    PURIFIER_HOT_COOL_M = "527M"  
    PURIFIER_BIG_QUIET = "664"  


class DeviceName(Enum): # TODO: Disambiguate these names
    DeviceType.VAC_360_HEURIST = "360 Heurist robot vacuum"
    DeviceType.VAC_360_EYE = "360 Eye robot vacuum"
    DeviceType.VAC_360_VIS_NAV = "360 Vis Nav robot vacuum"
    DeviceType.PURE_COOL = "Pure Cool Series (TP04/TP07/TP09/TP11/PC1)"
    DeviceType.PURIFIER_COOL_K = "Purifier Cool K Series"
    DeviceType.PURIFIER_COOL_E = "Purifier Cool E Series"
    DeviceType.PURIFIER_COOL_M = "Purifier Cool M Series"
    DeviceType.PURE_COOL_DESK = "Pure Cool Link Desk"
    DeviceType.PURE_COOL_LINK = "Pure Cool Link"
    DeviceType.PURE_COOL_LINK_DESK = "Pure Cool Link Desk"
    DeviceType.PURE_HOT_COOL = "Pure Hot+Cool Series (HP04/HP07/HP09)"
    DeviceType.PURIFIER_HOT_COOL_E = "Pure Hot+Cool E Series (Deprecated - use Pure Hot+Cool)"
    DeviceType.PURE_HOT_COOL_LINK = "Pure Hot+Cool Link"
    DeviceType.PURE_HUMIDIFY_COOL = "Pure Humidify+Cool Series (PH01/PH02/PH03/PH04)"
    DeviceType.PURIFIER_HUMIDIFY_COOL_K = "Purifier Humidify+Cool K Series (Deprecated - use Pure Humidify+Cool)"
    DeviceType.PURIFIER_HUMIDIFY_COOL_E = "Purifier Humidify+Cool E Series (Deprecated - use Pure Humidify+Cool)"
    DeviceType.PURIFIER_HOT_COOL_K = "Purifier Hot+Cool K Series (Deprecated - use Pure Hot+Cool)"
    DeviceType.PURIFIER_BIG_QUIET = "Purifier Big+Quiet Series"
